### ISSUE TITLE
Please update dist-tags in npm registry to accurately reflect versions for github repo

### ISSUE THREAD

**Issue by hulkish** [spiralx/jshint-summary#1]
The jshint-summary module seems to only allow for install of v0.1.2. I took a look at https://registry.npmjs.org/jshint-summary and verified. I'd like to use 0.3.0 but cant unless I were to pull the repo and customize it so I can use it as a local dep.

Please update the npm registry! :)

**Comment by spiralx** [comment]
Obviously too busy coding and not enough checking... let me double-check everything's in order, I'll hopefully sort that out in a minute :)

**Comment by spiralx** [comment]
Ok, that all seems to be fine, I've just updated it in npm, you should be able to get v0.3.0 now - let me know of any issues!

**Comment by hulkish** [comment]
Thanks for the quick turnaround. It's working as expected now.

**Comment by spiralx** [comment]
I was at the computer, and it only took a minute or so! ;)
